### ISSUE TITLE
Compilation error: 'ledcSetup' was not declared in this scope; did you mean 'ledc_stop'?

### ISSUE THREAD

**Issue by Crazy38TR** [spawn451/ESP32-CAM_Audio#4]
Hello, I was using your project in my home before. Now when I want to use the project again, I get an error. Can you help me?

Error Message:

`F:\30.05.2024 Downloads\Compressed\ESP32-CAM_Audio-main\ESP32-CAM_Audio\app_httpd.cpp: In function 'void setupLedFlash(int)':
F:\30.05.2024 Downloads\Compressed\ESP32-CAM_Audio-main\ESP32-CAM_Audio\app_httpd.cpp:1390:5: error: 'ledcSetup' was not declared in this scope; did you mean 'ledc_stop'?
 1390 |     ledcSetup(LED_LEDC_CHANNEL, 5000, 8);
      |     ^~~~~~~~~
      |     ledc_stop
F:\30.05.2024 Downloads\Compressed\ESP32-CAM_Audio-main\ESP32-CAM_Audio\app_httpd.cpp:1391:5: error: 'ledcAttachPin' was not declared in this scope; did you mean 'ledcAttach'?
 1391 |     ledcAttachPin(pin, LED_LEDC_CHANNEL);
      |     ^~~~~~~~~~~~~
      |     ledcAttach

exit status 1

Compilation error: 'ledcSetup' was not declared in this scope; did you mean 'ledc_stop'?`

**Comment by madkrystiank** [comment]
?

**Comment by madkrystiank** [comment]
https://forum.arduino.cc/t/ledcsetup-with-esp32-core-v3-0-0-not-work/1266221/3 

This?

**Comment by madkrystiank** [comment]
comment this lines

void setupLedFlash(int pin) 
{
    #if CONFIG_LED_ILLUMINATOR_ENABLED
    //== DISABLE LED
    //ledcSetup(LED_LEDC_CHANNEL, 5000, 8);
    //ledcAttachPin(pin, LED_LEDC_CHANNEL);
    #else
    log_i("LED flash is disabled -> CONFIG_LED_ILLUMINATOR_ENABLED = 0");
    #endif
}

**Comment by spawn451** [comment]
Sorry for the late response. It's been a long time since I logged in.  I close the issue as you find the solution :)
